---
title: "Wavefront Shaping Through Flexible Multicore Fibers Bundles: Summer 2025 Quarto Report"
html:
  number-sections: false
header-includes:
  - \setcounter{page}{1} 
---

# Table of Contents {.unnumbered}
1. [Index](index.qmd)
2. [Abstract](/sections/abstract/abstract.qmd)
3. [Introduction](/sections//introduction/introduction.qmd)  
&nbsp;&nbsp;&nbsp;&nbsp; 3.1 [Multicore Fibers and Phase Distortions](/sections/introduction/introduction.qmd#multicore-fibers-and-phase-distortion)     
&nbsp;&nbsp;&nbsp;&nbsp; 3.2 [Off-Axis Holography for Phase Measurement](/sections/introduction/introduction.qmd#off-axis-holography-for-phase-measurement)      
&nbsp;&nbsp;&nbsp;&nbsp; 3.3 [High-Quality Interference](/sections//introduction/introduction.qmd#high-quality-interference)         
4. [Methods](/sections//methods/methods.qmd)    
&nbsp;&nbsp;&nbsp;&nbsp; 4.1 [Initial Setup and Improvements](/sections/methods/methods.qmd#initial-setup-and-improvements)    
&nbsp;&nbsp;&nbsp;&nbsp; 4.2 [Ben Hartley's MCF Setup](/sections/methods/methods.qmd#ben-hartleys-mcf-setup)        
5. [Results](/sections/results/results.qmd)    
&nbsp;&nbsp;&nbsp;&nbsp; 5.1 [System Optimization](/sections/results/results.qmd#system-optimization)    
&nbsp;&nbsp;&nbsp;&nbsp; 5.2 [Bend Experiment](/sections/results/results.qmd#bend-experiment)         
6. [Conclusion](/sections/conclusion/conclusion.qmd)
7. [Acknowledgements](/sections/acknowledgements/acknowledgements.qmd)
8. [Appendix](/sections/appendix/appendix.qmd)  
&nbsp;&nbsp;&nbsp;&nbsp; 8.1 [Off-Axis Holography Simulations](/sections/appendix/appendix.qmd#simulations)   
&nbsp;&nbsp;&nbsp;&nbsp; 8.2 [Python and MATLAB Scripts](/sections/appendix/appendix.qmd#python-and-matlab-code)  
&nbsp;&nbsp;&nbsp;&nbsp; 8.3 [Camera and SLM](/sections/appendix/appendix.qmd#camera-and-slm)