---
title: Abstract
output-file: index
header-includes:
  - \setcounter{page}{2}  
---

Traditional optical systems used in endoscopic imaging face significant challenges in delivering high-resolution light through compact and flexible media. Multicore fibers (MCFs) offer a promising alternative by transmitting light through multiple cores, enabling coherent lensless imaging and precise light delivery. However, bending in MCFs introduces complex wavefront distortions that must be corrected for accurate imaging. This project investigates how off-axis holography and wavefront shaping techniques can mitigate phase distortions in MCFs, enabling high-resolution, minimally invasive optical imaging, and neural stimulation. Interference patterns between the reference and sample beams, captured via off-axis holography, were analyzed in the Fourier domain to extract the phase information of the MCF. By isolating and recentralizing the +1 diffraction order from the interference pattern in the Fourier domain, effective phase retrieval was achieved, revealing the extent of bend-induced distortions. To address these distortions, a spatial light modulator (SLM) was used to apply corrective wavefronts with the goal of restoring focused light at the fiber output. Bending significantly degrades phase integrity, but this research demonstrates that off-axis holography combined with SLM-based wavefront shaping offers an effective solution. The ability to focus light through flexible MCFs has major implications for biomedical imaging and optogenetics. These applications include high-resolution deep-brain imaging and precise light delivery, advancing tools for minimally invasive neuroscience. 